sudo: false
language: node_js
node_js:
- '10'
branches:
  only:
  - master
cache:
  directories:
  - node_modules
before_install:
- yarn upgrade
install:
- yarn install
script:
- yarn test
- yarn coveralls